spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dev
    username: dev-user
    password: passdev
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: com_database_create.sql