spring:
  datasource:
    url: jdbc:mysql://localhost:3307/prod
    username: prod-user
    password: passprod
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false